name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy

    - name: Install protoc
      run: |
        sudo apt-get install -y protobuf-compiler
        protoc --version

    - uses: actions/checkout@v3
    
    - name: Rustfmt
      uses: actions-rs/cargo@v1
      with:
        toolchain: stable
        command: fmt
        args: --all --check

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.5.0
      with:
        cache-on-failure: true
        cache-all-crates: true
            
    - name: Build
      run: cargo check --release
    - name: Run tests
      run: cargo test --release --locked --verbose --all
